### ISSUE TITLE
can we have a local demo that we can dial into?

### ISSUE THREAD

**Issue by x37v** [kra/futel-installation#259]
could it be as easy as:
`make demo` or something simple that builds all the assets and launches vagrant and then indicates how you can dial into your VM?

maybe there is already a way to do this? can we do it without any secret special files? it is really not clear.

**Comment by kra** [comment]
This is an important issue and I want to get to a place, or realistically close, where someone can walk up and get a VM with minimal input from me.

You will always need the secrets files in conf. This was the part of the docs that was roughest when i was telling the last person how to get set up. I've updated the README to mention the exact files as a requirement.

Everything else should be listed in README.virtualbox (and its pointer to the requirements in README). So could you start here:

https://github.com/kra/futel-installation/blob/master/asteriskserver/README.virtualbox#L3

and get the 2 secrets files from me, and tell me where you get blocked.

I'd like to have a Makefile or ansible recipe, but I haven't bothered because that would only cover the 5 commands which are the actual install:

https://github.com/kra/futel-installation/blob/master/asteriskserver/README.virtualbox#L23

and that's not where anyone gets tripped up, the hard part is the requirements. And that's ubuntu-specific. Maybe we could have an ansible recipe for the pip and gem parts? An ansible recipe could also automatically fail if the conf files aren't present and tell you want is needed.

One other small part is that IIRC your fork had that subordinate git repo thing that I didn't merge in because I needed to keep it simple while making some changes, so that's another manual step:

https://github.com/kra/futel-installation/blob/master/asteriskserver/README.virtualbox#L19

I forgot how to do that subordinate git repo thing, but if you could make a pull request to put that in again, that's one less manual step, which would be good.

**Comment by kra** [comment]
README.virtualbox now has simpler commands that should tell you what is missing when you try it. If you're blocked or it needs something, re-open this or open an new issue and I'll work it out with you.
