### ISSUE TITLE
make separate contexts for outgoing extensions

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#66]
hooked up a HT701 to test it, had it going to the usual default-outgoing context, autodialling an extension in the device to get the menu on pickup. I was able to get a dialtone in default-outgoing by flashing rapidly. This would let me connect to any extension in default-outgoing, including the admin menu.

I don't know if the SPA2s have this problem, they use a dialplan. The HT701 autodial is probably just sending DTMF or something cheesy.

Fix:
- keep demo/test extensions in default-outgoing, just treat them as slightly dangerous if used for public phones
- give our known extensions the specific contexts instead of default-outgoing, dunno if we want/need to keep the interim context or what - just give them fewer choices, or one choice

**Comment by Brandon314** [comment]
I've found it's fairly hard (potentially impossible) to bypass the dialplans in the devices that support them (the D-link vonage boxes, PAP2T, etc.). I specifically set a delay before auto-dialing an extension so that I could dial whatever I want (for diagnostics/power users in the field) but if I wanted to clamp it down, I'd drop the pause and AFAIK put the clamps on the options a user could touch. The dial-plan can be so sparse that it won't even accept any DTMF/Key-Presses (until the call is connected of course)....so seems secure.

**Comment by kra** [comment]
yeah, I don't know what these HT701s are doing, the dialplan didn't support S0<:999>, instead there's a separate field, which I was able to bypass as described. The other vulnerability would be someone editing the dialplan, or accessing the SIP password and using it for their own device.

I don't expect any of this will be likely in real life. The bigger risk is users getting confused by an HT701 style unexpected bypass, having its own context would help.

**Comment by kra** [comment]
Would this even work for our various ATAs? Probably does if they accept a dialplan of just S0 or something. But then we couldn't change the destination without changing the SIP ID, which means the SIP IDs wouldn't be by location anymore, they'd change.
