### ISSUE TITLE
outgoing call timeouts not effective

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#77]
voip.ms cdr

2016-06-04 09:29:46	"668" <15037644393>	<redacted>	United States	2:17:11	* 0.0100	1.3720

we expect this to have a timeout in sip.conf

setvar=call_timeout=300

what is this doing, 300 mnutes? Make it 30 minutes for default and 60 for r2d2.

**Comment by lboom** [comment]
Hmmm... maybe the timeout parameter isn't doing what we thought it was doing.

This is from: http://www.voip-info.org/wiki/view/Asterisk+cmd+Dial

The timeout parameter is optional. If not specifed, the Dial command will wait indefinitely, exiting only when the originating channel hangs up, or all the dialed channels return a busy or error condition. Otherwise it specifies a maximum time, in seconds, that the Dial command is to wait for a channel to answer.

**Comment by kra** [comment]
prospective installation wants this

**Comment by kra** [comment]
http://www.voip-info.org/wiki/view/Asterisk+cmd+Dial

we want the L option, not the timeout arg we are using

L(x[:y][:z]): Limit the call to 'x' ms, warning when 'y' ms are left, repeated every 'z' ms) Only 'x' is required, 'y' and 'z' are optional. Numbers must be integers- beware of AGI scripts that may return long integers in scientific notation (esp PHP 5.2.5&6) The following special variables are optional for limit calls: (pasted from app_dial.c)
LIMIT_PLAYAUDIO_CALLER - yes|no (default yes) - Play sounds to the caller.
LIMIT_PLAYAUDIO_CALLEE - yes|no - Play sounds to the callee.
LIMIT_TIMEOUT_FILE - File to play when time is up.
LIMIT_CONNECT_FILE - File to play when call begins.
LIMIT_WARNING_FILE - File to play as warning if 'y' is defined. If LIMIT_WARNING_FILE is not defined, then the default behaviour is to announce ("You have [XX minutes] YY seconds").
